/**
 * OsdModal.tsx — burned-in overlays, ported from the legacy csLoadOsd /
 * osdRender / osdApply.
 *
 * Fields are rendered per overlay only where the camera exposes them: the text
 * box appears for Plain overlays, the format boxes only when the camera reports
 * a format. Sending a field the camera has no node for is a 502, so "not shown"
 * is load-bearing, not cosmetic.
 *
 * (The legacy osdApply wrote the read-back unguarded — `_osds[i] = r.osd` — so a
 * failed re-read stored `undefined` and the next render threw on `o.text_type`.
 * Guarded here.)
 */
import { useState } from 'react';
import { apiFetch } from '@/lib/api';
import { Modal } from '@/components/Modal';
import { useToast } from '@/components/Toast';
import type { Camera } from '@/lib/types';
import {
  ErrorState, Label, Loading, OSD_POSITIONS, useOnvif, type Osd,
} from './onvif';

interface OsdResp { osds: Osd[] }

function OsdCard({ camId, osd, onSaved, onError }: {
  camId: string;
  osd: Osd;
  onSaved: (o: Osd) => void;
  onError: (m: string) => void;
}) {
  const toast = useToast();
  const o = osd;
  const [d, setD] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);

  const cur = (k: string, was: string | null) => (d[k] !== undefined ? d[k] : (was ?? ''));
  const set = (k: string, v: string) => setD(s => ({ ...s, [k]: v }));

  const isPlain = o.text_type === 'Plain';
  const hasDate = o.date_format != null;
  const hasTime = o.time_format != null;

  async function apply() {
    const changes: Record<string, string> = {};
    if (isPlain && cur('text', o.text) !== (o.text ?? '')) changes.text = cur('text', o.text);
    if (hasDate && cur('date', o.date_format) !== o.date_format) changes.date_format = cur('date', o.date_format);
    if (hasTime && cur('time', o.time_format) !== o.time_format) changes.time_format = cur('time', o.time_format);
    const pos = cur('pos', o.position);
    if (pos && pos !== o.position) changes.position = pos;

    if (!Object.keys(changes).length) { toast('Nothing changed'); return; }
    setBusy(true);
    try {
      const resp = await apiFetch<{ osd: Osd | null }>(
        `/cameras/${camId}/osd/${encodeURIComponent(o.token || '')}`,
        { method: 'PUT', body: JSON.stringify(changes) },
      );
      if (resp.osd) onSaved(resp.osd);  // guard: a failed read-back must not blank the card
      setD({});
      toast('OSD updated');
    } catch (e: any) {
      onError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="card" style={{ marginBottom: 12 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 10 }}>
        <b style={{ fontSize: 13.5 }}>{o.text_type || o.type || 'OSD'} overlay</b>
        <code style={{ marginLeft: 'auto', fontSize: 10, color: 'var(--dim)' }}>{o.token}</code>
      </div>

      {o.type === 'Image' ? (
        <div style={{ fontSize: 12.5, color: 'var(--muted)' }}>
          This is an image overlay — only its position can be changed here.
        </div>
      ) : !isPlain && !hasDate && !hasTime ? (
        <div style={{ fontSize: 12.5, color: 'var(--muted)' }}>
          This overlay’s text is generated by the camera ({o.text_type}) — only its position can be changed.
        </div>
      ) : null}

      <div className="form-grid">
        {isPlain && (
          <div className="form-group full">
            <Label>Text</Label>
            <input maxLength={255} value={cur('text', o.text)} onChange={e => set('text', e.target.value)} />
          </div>
        )}
        {hasDate && (
          <div className="form-group">
            <Label>Date format</Label>
            <input value={cur('date', o.date_format)} onChange={e => set('date', e.target.value)} />
          </div>
        )}
        {hasTime && (
          <div className="form-group">
            <Label>Time format</Label>
            <input value={cur('time', o.time_format)} onChange={e => set('time', e.target.value)} />
          </div>
        )}
        <div className="form-group">
          <Label>Position</Label>
          <select value={cur('pos', o.position)} onChange={e => set('pos', e.target.value)}>
            {!o.position && <option value="">—</option>}
            {OSD_POSITIONS.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
        </div>
      </div>

      <div className="form-actions">
        <button className="btn-primary btn-sm" onClick={apply} disabled={busy}>
          {busy ? <span className="spinner" /> : 'Apply'}
        </button>
      </div>
    </div>
  );
}

export function OsdModal({ camera, onClose, onOpenMaintenance }: {
  camera: Camera;
  onClose: () => void;
  onOpenMaintenance: () => void;
}) {
  const { data, setData, err, setErr, loading } = useOnvif<OsdResp>(`/cameras/${camera.id}/osd`);
  const osds = data?.osds ?? [];

  return (
    <Modal open title={`OSD overlays — ${camera.name}`} onClose={onClose} width={620}>
      {loading && <Loading />}
      {!loading && err && <ErrorState message={err} onOpenMaintenance={onOpenMaintenance} />}
      {!loading && !err && !osds.length && (
        <div className="empty">This camera has no overlays configured.</div>
      )}
      {!loading && !err && osds.map((o, i) => (
        <OsdCard key={o.token || i} camId={camera.id} osd={o}
          onError={setErr}
          onSaved={no => setData(d => d && {
            ...d, osds: d.osds.map((x, j) => (j === i ? no : x)),
          })} />
      ))}
      {!loading && !err && !!osds.length && (
        <div className="d-hint">
          Overlays are burned into the video by the camera itself — they appear in recordings and clip exports
          (evidentiary timestamps). Formats use the camera’s own tokens, e.g. <code>MM/dd/yyyy</code> and{' '}
          <code>HH:mm:ss</code>.
        </div>
      )}
    </Modal>
  );
}
