"""sync-client.py — one-shot, idempotent Keycloak realm sync (stdlib only).

Keycloak imports realm-vms.json ONLY on its first boot with an empty database,
so any deployment that ever started with an older realm file keeps that config
forever. This runs as a one-shot compose service on EVERY `up` and reconciles
the six things that have bitten us:

  1. vms-web redirectUris/webOrigins — the original realm shipped
     redirectUris="*" + webOrigins="+", and "+" (derive origins from redirect
     URIs) can't derive anything from a wildcard, so the token endpoint sent no
     CORS headers and the SPA died with the opaque "Login failed: undefined".

  2. Realm roles — supervisor/viewer were added after the first release, so
     existing realms don't have them and the Roles & permissions matrix would
     show roles nobody can actually be assigned.

  3. The vms-pwcheck client — confidential, direct-grant-only, used by the api
     to verify a user's CURRENT password when they change it themselves. It
     exists so vms-web (a PUBLIC client) never needs direct access grants
     enabled, which would let anyone on the LAN trade credentials for tokens
     straight at the token endpoint. Its secret is generated by Keycloak and
     read back by the api over the admin API — it is never stored in .env.

  4. The VERIFY_PROFILE required action — kept ON so a user created without an
     email is prompted to add it at first login. See sync_required_actions().

  5. Realm login flags — rememberMe and internationalization (en/hi). The login
     theme renders a "remember this workstation" switch and a language switcher,
     and Keycloak emits NEITHER unless the realm enables them.

  6. The realm displayName — the product name shown on the sign-in page. This
     is white-label, set from BRAND_NAME, and is the ONLY place the login page
     can get it from: Keycloak is a separate service and cannot read the SPA's
     compiled-in brand. See sync_realm_brand().

Already-correct deployments log "already in sync". Always exits 0 — a failed
sync must never block the stack.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

BASE = os.environ.get("KC_URL", "http://127.0.0.1:8085").rstrip("/")
USER = os.environ.get("KEYCLOAK_ADMIN", "admin")
PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "admin")
REALM = os.environ.get("KC_REALM", "vms")
CLIENT_ID = os.environ.get("KC_CLIENT_ID", "vms-web")
PWCHECK_CLIENT_ID = "vms-pwcheck"
# Product name for the sign-in page. Same value the SPA is built with (compose
# passes it to both). Empty/unset means "leave whatever the realm has" — an
# operator who renamed the realm by hand does not get it reverted on next `up`.
BRAND_NAME = os.environ.get("BRAND_NAME", "").strip()
WANT_REDIRECTS = ["*"]
WANT_ORIGINS = ["*"]
# Client attributes that must survive a realm upgrade. post.logout.redirect.uris
# is validated SEPARATELY from redirectUris at the end-session endpoint, so an
# empty value rejects every logout with "Invalid redirect uri" even though login
# (which uses redirectUris) works. "+" means "inherit the valid redirect URIs",
# matching redirectUris=["*"]. realm-vms.json ships both, but that file is only
# read on a first-boot import — existing realms never got them.
WANT_ATTRS = {
    "post.logout.redirect.uris": "+",
    "pkce.code.challenge.method": "S256",
}

# Must stay in step with backend/services/keycloak_admin.py PRODUCT_ROLES.
WANT_ROLES = {
    "admin": "Configure cameras, users, retention, integrations",
    "supervisor": "Everything an operator can do, plus acknowledge and reset alarms",
    "operator": "View, search, acknowledge alarms, trigger peripherals",
    "viewer": "Live view only — no recorded footage, no exports",
    "dpo": "Data Protection Officer / Authority — approve sensitive actions",
}

PWCHECK_REP = {
    "clientId": PWCHECK_CLIENT_ID,
    "name": "VMS password verification (internal)",
    "description": "Confidential, direct-grant-only client the api uses to verify a "
                   "user's CURRENT password when they change it themselves. Never used "
                   "by a browser. Keeps vms-web free of direct grants.",
    "enabled": True,
    "publicClient": False,
    "standardFlowEnabled": False,
    "implicitFlowEnabled": False,
    "directAccessGrantsEnabled": True,
    "serviceAccountsEnabled": False,
    "fullScopeAllowed": False,
    "redirectUris": [],
    "webOrigins": [],
}


def call(url: str, data: bytes | None = None, headers: dict | None = None,
         method: str | None = None):
    req = urllib.request.Request(url, data=data, headers=headers or {}, method=method)
    return urllib.request.urlopen(req, timeout=10)


def log(msg: str) -> None:
    print(f"keycloak-client-sync: {msg}", flush=True)


def sync_web_client(auth: dict) -> None:
    """1. vms-web must have concrete redirectUris + webOrigins (not "+"), and the
    post-logout / PKCE attributes an upgraded realm never imported."""
    clients = json.load(call(
        f"{BASE}/admin/realms/{REALM}/clients?clientId={urllib.parse.quote(CLIENT_ID)}",
        headers=auth,
    ))
    if not clients:
        log(f"client '{CLIENT_ID}' not found in realm '{REALM}' — skipping")
        return
    client = clients[0]
    attrs = client.get("attributes") or {}
    attrs_ok = all(attrs.get(k) == v for k, v in WANT_ATTRS.items())
    if (client.get("redirectUris") == WANT_REDIRECTS
            and client.get("webOrigins") == WANT_ORIGINS and attrs_ok):
        log(f"'{CLIENT_ID}' already in sync")
        return
    before = (client.get("redirectUris"), client.get("webOrigins"),
              attrs.get("post.logout.redirect.uris"))
    client["redirectUris"] = WANT_REDIRECTS
    client["webOrigins"] = WANT_ORIGINS
    # Merge, don't replace — keep any other attributes Keycloak set itself.
    client["attributes"] = {**attrs, **WANT_ATTRS}
    call(f"{BASE}/admin/realms/{REALM}/clients/{client['id']}",
         data=json.dumps(client).encode(), headers=auth, method="PUT")
    log(f"updated '{CLIENT_ID}': redirectUris/webOrigins/post-logout {before} "
        f"-> (['*'], ['*'], '+')")


def sync_roles(auth: dict) -> None:
    """2. Every product role must exist as a realm role."""
    existing = {
        r["name"] for r in
        json.load(call(f"{BASE}/admin/realms/{REALM}/roles?max=200", headers=auth))
    }
    created = []
    for name, description in WANT_ROLES.items():
        if name in existing:
            continue
        call(f"{BASE}/admin/realms/{REALM}/roles",
             data=json.dumps({"name": name, "description": description}).encode(),
             headers=auth, method="POST")
        created.append(name)
    if created:
        log(f"created realm role(s): {', '.join(created)}")
    else:
        log("realm roles already in sync")


def sync_pwcheck_client(auth: dict) -> None:
    """3. The confidential password-verification client must exist with direct
    grants on. Its secret stays inside Keycloak — the api reads it back."""
    clients = json.load(call(
        f"{BASE}/admin/realms/{REALM}/clients?clientId={urllib.parse.quote(PWCHECK_CLIENT_ID)}",
        headers=auth,
    ))
    if not clients:
        call(f"{BASE}/admin/realms/{REALM}/clients",
             data=json.dumps(PWCHECK_REP).encode(), headers=auth, method="POST")
        log(f"created client '{PWCHECK_CLIENT_ID}' (self-service password change)")
        return
    client = clients[0]
    # Repair the two settings that make or break the direct grant.
    if client.get("directAccessGrantsEnabled") and not client.get("publicClient"):
        log(f"'{PWCHECK_CLIENT_ID}' already in sync")
        return
    client.update(directAccessGrantsEnabled=True, publicClient=False)
    call(f"{BASE}/admin/realms/{REALM}/clients/{client['id']}",
         data=json.dumps(client).encode(), headers=auth, method="PUT")
    log(f"repaired '{PWCHECK_CLIENT_ID}': directAccessGrants=on, publicClient=off")


def sync_required_actions(auth: dict) -> None:
    """4. Keep the VERIFY_PROFILE required action ON.

    This is the intended UX: email is optional when an admin creates a user, and
    VERIFY_PROFILE prompts that user to fill it in at their FIRST login, before
    they reach the dashboard.

    (An earlier version of this step DISABLED it, believing it broke the
    api's password-verification direct grant — that grant returns
    `invalid_grant: Account is not fully set up` for a profile-less user. But
    with VERIFY_PROFILE on, a profile-less user can't finish logging in in the
    first place, so anyone actually holding a session — the only ones who can
    reach the self-service password change — has already completed their profile
    and has an email, and the grant succeeds. verify_password() still handles the
    incomplete-account case defensively, returning a clear 409.)

    Keycloak ships VERIFY_PROFILE enabled, so this only has to re-enable it on a
    realm where that earlier step turned it off.
    """
    actions = json.load(call(
        f"{BASE}/admin/realms/{REALM}/authentication/required-actions", headers=auth))
    for a in actions:
        if a.get("alias") != "VERIFY_PROFILE":
            continue
        if a.get("enabled"):
            log("VERIFY_PROFILE already enabled")
            return
        a["enabled"] = True
        call(f"{BASE}/admin/realms/{REALM}/authentication/required-actions/VERIFY_PROFILE",
             data=json.dumps(a).encode(), headers=auth, method="PUT")
        log("re-enabled the VERIFY_PROFILE required action "
            "(prompts new users to complete their email at first login)")
        return
    log("VERIFY_PROFILE action not present — nothing to do")


def sync_realm_login(auth: dict) -> None:
    """5. Realm flags the login theme's design depends on.

    The split-screen sign-in renders a "Remember this workstation" switch and an
    EN/हिं language switcher — but Keycloak only emits the rememberMe checkbox
    when realm.rememberMe is on, and only emits locale links when
    internationalizationEnabled is on. Without these the theme silently drops
    both controls, so they are part of the design, not a preference.
    """
    realm = json.load(call(f"{BASE}/admin/realms/{REALM}", headers=auth))
    want = {
        "rememberMe": True,
        "internationalizationEnabled": True,
        "supportedLocales": ["en", "hi"],
        "defaultLocale": "en",
        "loginTheme": "vms",
    }
    if all(realm.get(k) == v for k, v in want.items()):
        log("realm login settings already in sync")
        return
    realm.update(want)
    call(f"{BASE}/admin/realms/{REALM}",
         data=json.dumps(realm).encode(), headers=auth, method="PUT")
    log("updated realm login settings (rememberMe, i18n en/hi, vms theme)")


def sync_realm_brand(auth: dict) -> None:
    """6. The product name on the sign-in page (realm displayName).

    login/template.ftl renders ${realm.displayName}, so the name in the SPA
    bundle has no bearing on it — the two drift the moment either changes.
    realm-vms.json carries the right value, but Keycloak reads that file ONLY
    when importing a realm that does not yet exist, so every already-running
    box keeps its original name forever. Reconciling here is what actually
    keeps the login page and the console showing the same product.

    displayNameHtml is set alongside it: Keycloak prefers it where both exist,
    so updating only displayName leaves the old name rendering in any theme
    that uses the HTML variant.
    """
    if not BRAND_NAME:
        log("BRAND_NAME unset — leaving realm displayName as-is")
        return
    realm = json.load(call(f"{BASE}/admin/realms/{REALM}", headers=auth))
    # Escaped, not interpolated: the value comes from .env and lands in a field
    # Keycloak renders as raw HTML on the login page.
    safe = (BRAND_NAME.replace("&", "&amp;").replace("<", "&lt;")
                      .replace(">", "&gt;"))
    want = {"displayName": BRAND_NAME, "displayNameHtml": safe}
    if all(realm.get(k) == v for k, v in want.items()):
        log(f"realm displayName already in sync ({BRAND_NAME})")
        return
    realm.update(want)
    call(f"{BASE}/admin/realms/{REALM}",
         data=json.dumps(realm).encode(), headers=auth, method="PUT")
    log(f"updated realm displayName -> {BRAND_NAME}")


def sync_seed_passwords(auth: dict) -> None:
    """7. Replace the realm's SHIPPED seed passwords with generated ones.

    realm-vms.json seeds two users so a fresh appliance is usable at all:
    `admin` (roles admin+operator+dpo) and `operator`. Their passwords were
    hardcoded literals in a committed file — `admin`/`admin` and
    `operator`/`operator` — and nothing rotated them, so every clone of this
    product booted with the same working full-admin login on a video
    surveillance system. gen-secrets.sh took care of INTERNAL_API_KEY,
    KEYCLOAK_ADMIN_PASSWORD and DISCOVERY_SECRET_KEY, and walked straight past
    the one an attacker would actually type.

    Done here rather than by realm-import substitution because this runs with
    admin rights on every `up` and its effect can be VERIFIED, whereas an
    unexpanded `${env.X}` in the realm JSON would silently become the literal
    password — a worse default than the one being replaced.

    Idempotent, and deliberately one-shot per user: the `vms_seed_pw`
    attribute marks a user whose seed password has been retired, so a later
    `up` never clobbers a password the operator has since chosen themselves.
    """
    for username, var in (("admin", "VMS_ADMIN_PASSWORD"),
                          ("operator", "VMS_OPERATOR_PASSWORD")):
        secret = os.environ.get(var, "").strip()
        if not secret:
            log(f"WARNING {var} is unset — '{username}' keeps the SHIPPED "
                f"password from realm-vms.json. Set it in .env and re-run, or "
                f"change it in the console now.")
            continue

        found = json.load(call(
            f"{BASE}/admin/realms/{REALM}/users"
            f"?username={urllib.parse.quote(username)}&exact=true", headers=auth))
        if not found:
            log(f"user '{username}' not present — nothing to rotate")
            continue
        user = found[0]

        attrs = user.get("attributes") or {}
        if attrs.get("vms_seed_pw") == ["rotated"]:
            log(f"'{username}' seed password already retired")
            continue

        call(f"{BASE}/admin/realms/{REALM}/users/{user['id']}/reset-password",
             data=json.dumps({"type": "password", "value": secret,
                              "temporary": False}).encode(),
             headers=auth, method="PUT")

        attrs["vms_seed_pw"] = ["rotated"]
        user["attributes"] = attrs
        call(f"{BASE}/admin/realms/{REALM}/users/{user['id']}",
             data=json.dumps(user).encode(), headers=auth, method="PUT")
        log(f"retired the shipped password for '{username}' "
            f"(now the generated {var})")


def main() -> None:
    deadline = time.time() + 180
    while True:
        try:
            call(f"{BASE}/realms/{REALM}")
            break
        except Exception:
            if time.time() > deadline:
                log(f"keycloak not reachable at {BASE} after 180s — skipping")
                return
            time.sleep(3)

    body = urllib.parse.urlencode({
        "client_id": "admin-cli", "username": USER,
        "password": PASSWORD, "grant_type": "password",
    }).encode()
    try:
        token = json.load(
            call(f"{BASE}/realms/master/protocol/openid-connect/token", data=body)
        )["access_token"]
    except urllib.error.HTTPError as exc:
        log(f"master admin login failed (HTTP {exc.code}) — is KEYCLOAK_ADMIN_PASSWORD "
            "in .env the real console password? skipping")
        return

    auth = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    # Each step is independent — one failing must not skip the others.
    for step in (sync_web_client, sync_roles, sync_pwcheck_client,
                 sync_required_actions, sync_realm_login, sync_realm_brand,
                 sync_seed_passwords):
        try:
            step(auth)
        except Exception as exc:  # noqa: BLE001
            log(f"{step.__name__} failed: {exc} — continuing")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001 — never block the stack
        log(f"unexpected error: {exc} — skipping")
    sys.exit(0)
