"""tlsutil.py — TLS certificate fingerprinting for RTSPS camera sources.

Some cameras serve RTSP over TLS on :554 and reject plaintext RTSP outright —
CP-Plus/Dahua OEM units ship this way, and a plain DESCRIBE gets a TLS fatal
alert that surfaces downstream as "connection reset by peer".  Those devices
present self-signed certificates, often with a CN/SAN that doesn't even match
the address they answer on (a unit can advertise CN=192.0.2.10 while serving
.11), so MediaMTX refuses them:

    tls: failed to verify certificate: x509: certificate is valid for
    192.0.2.10, ... not 192.0.2.11

MediaMTX has no "skip verification" switch for RTSP sources; pinning the
certificate's SHA-256 fingerprint via a path's ``sourceFingerprint`` is the
only way to pull such a stream.

The fingerprint is read off the live socket at add_path time rather than stored
in the registry, so a certificate regenerated by a firmware update or factory
reset heals on the next reconnect instead of wedging the stream until someone
re-runs discovery.  On a camera LAN this buys reconnect stability, not
authentication — the same trust posture onvif_probe already takes for these
devices (``session.verify = False``).
"""
from __future__ import annotations

import asyncio
import hashlib
import socket
import ssl
from typing import Optional
from urllib.parse import urlparse

import structlog

log = structlog.get_logger(__name__)

# Deliberately tight: this runs on the failure path of rtsp_verify, where a
# filtered host would otherwise add its full timeout to every candidate probed.
# A camera on the same LAN handshakes in milliseconds, and a device that isn't
# speaking TLS resets immediately.
_HANDSHAKE_TIMEOUT = 3.0
_DEFAULT_RTSPS_PORT = 322  # RFC 7826 registers 322 for rtsps; cameras mostly use 554


def _unverified_context() -> ssl.SSLContext:
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    # check_hostname must be cleared BEFORE verify_mode — the reverse order
    # raises, since CERT_NONE is illegal while hostname checking is on.
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def _fingerprint_sync(host: str, port: int) -> Optional[str]:
    try:
        with socket.create_connection((host, port), timeout=_HANDSHAKE_TIMEOUT) as sock:
            sock.settimeout(_HANDSHAKE_TIMEOUT)
            with _unverified_context().wrap_socket(sock, server_hostname=host) as tls:
                der = tls.getpeercert(binary_form=True)
    except (OSError, ssl.SSLError) as exc:
        # Not a TLS endpoint, unreachable, or a handshake the device refused —
        # all mean "no fingerprint to pin", which callers treat as plain RTSP.
        log.debug("tls.fingerprint.miss", host=host, port=port, error=str(exc))
        return None
    if not der:
        return None
    return hashlib.sha256(der).hexdigest().upper()


async def cert_fingerprint(host: str, port: int) -> Optional[str]:
    """SHA-256 fingerprint of the certificate served at ``host:port``.

    Uppercase hex with no separators — the form MediaMTX's ``sourceFingerprint``
    expects.  Returns None when the endpoint doesn't complete a TLS handshake,
    which doubles as a cheap "does this port speak TLS?" probe.  Never raises.
    """
    try:
        return await asyncio.to_thread(_fingerprint_sync, host, port)
    except Exception as exc:  # noqa: BLE001 — a fingerprint is best-effort
        log.debug("tls.fingerprint.error", host=host, port=port, error=str(exc))
        return None


async def source_fingerprint(url: str) -> Optional[str]:
    """Fingerprint for an ``rtsps://`` source URL, or None for anything else.

    Plain ``rtsp://`` URLs return None without touching the network, so this is
    safe to call on every path config build.
    """
    try:
        parsed = urlparse(url)
    except ValueError:
        return None
    if parsed.scheme != "rtsps" or not parsed.hostname:
        return None
    return await cert_fingerprint(parsed.hostname, parsed.port or _DEFAULT_RTSPS_PORT)
