#!/usr/bin/env bash
# install-boot-resilience.sh — make the appliance come back after a power cut.
#
# Fixes two distinct faults, both observed live on 2026-08-26:
#
#   1. THE RACE.  The NVIDIA CDI spec lives at /var/run/cdi/nvidia.yaml, which
#      is tmpfs — wiped every boot and regenerated by the oneshot
#      nvidia-cdi-refresh.service. But that unit is ordered `After=
#      multi-user.target`, so it runs AFTER dockerd. Measured on this host:
#
#        17:17:01.204  dockerd: "CDI directory does not exist, skipping"
#        17:17:01.289  dockerd: "Loading containers: start."
#        17:17:05.969  nvidia-ctk: "Generated CDI spec with version 0.5.0"
#
#      dockerd starts every GPU container 4.7 s before the spec it needs exists,
#      and having skipped the directory it cannot even watch it for changes
#      ("failed to monitor for changes: no such file or directory").
#
#      Fix: move the spec to /etc/cdi/nvidia.yaml, which is on disk and
#      therefore already present when dockerd starts. NVIDIA supports this
#      directly — NVIDIA_CTK_CDI_OUTPUT_FILE_PATH is documented (commented out)
#      in nvidia-cdi-refresh.env, /etc/cdi is one of dockerd's two default CDI
#      spec dirs, and nvidia-cdi-refresh.path still regenerates the file on
#      every driver or toolkit upgrade. The race disappears rather than being
#      won more often.
#
#   2. THE CLASS.  `restart: unless-stopped` does not retry a container that
#      FAILED TO START, and Docker only auto-starts containers that were running
#      when the daemon last stopped. So one failed start — for any reason, not
#      just CDI — leaves the appliance down permanently. Fix: a systemd unit
#      that runs `./vms up -d` at boot, after both docker and the CDI refresh.
#
# Either half is useful alone; --cdi-only and --unit-only exist for that.
#
# Usage:
#   sudo scripts/install-boot-resilience.sh            # both (default)
#   sudo scripts/install-boot-resilience.sh --cdi-only
#   sudo scripts/install-boot-resilience.sh --unit-only
#   sudo scripts/install-boot-resilience.sh --uninstall
#   scripts/install-boot-resilience.sh --check         # no root needed
set -euo pipefail

VMS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE=/etc/nvidia-container-toolkit/nvidia-cdi-refresh.env
CDI_DIR=/etc/cdi
CDI_SPEC="$CDI_DIR/nvidia.yaml"
UNIT_SRC="$VMS_DIR/deploy/systemd/vms.service.in"
UNIT_DST=/etc/systemd/system/vms.service
MARKER='# --- added by VMS install-boot-resilience.sh ---'

MODE="${1:---all}"

say()  { printf '  %s\n' "$*"; }
head_() { printf '\n\033[1m%s\033[0m\n' "$*"; }
need_root() { [ "$(id -u)" -eq 0 ] || { echo "must run as root: sudo $0 $MODE" >&2; exit 1; }; }

has_nvidia() { [ -x /usr/bin/nvidia-ctk ] && command -v nvidia-smi >/dev/null 2>&1; }

# ── check ───────────────────────────────────────────────────────────────────
do_check() {
  head_ "CDI spec"
  if ! has_nvidia; then
    say "no NVIDIA toolkit on this host — the CDI half does not apply"
  else
    [ -f "$CDI_SPEC" ] \
      && say "OK      $CDI_SPEC exists (persistent, survives reboot)" \
      || say "MISSING $CDI_SPEC — GPU containers race dockerd on every boot"
    [ -f /var/run/cdi/nvidia.yaml ] \
      && say "note    /var/run/cdi/nvidia.yaml also present (tmpfs, harmless)"
    grep -qs "^NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=$CDI_SPEC" "$ENV_FILE" \
      && say "OK      nvidia-cdi-refresh writes to $CDI_SPEC" \
      || say "TODO    nvidia-cdi-refresh still writes to tmpfs"
  fi

  head_ "Boot unit"
  if systemctl list-unit-files vms.service >/dev/null 2>&1 \
     && [ -f "$UNIT_DST" ]; then
    say "OK      vms.service installed ($(systemctl is-enabled vms.service 2>/dev/null))"
  else
    say "MISSING vms.service — a failed container start is never retried"
  fi
  echo
}

# ── part 1: persistent CDI spec ─────────────────────────────────────────────
install_cdi() {
  head_ "1. Persistent CDI spec"
  if ! has_nvidia; then
    say "skipped — no NVIDIA container toolkit on this host"
    return 0
  fi
  [ -f "$ENV_FILE" ] || { say "skipped — $ENV_FILE not found (toolkit too old?)"; return 0; }

  if grep -q "^NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=" "$ENV_FILE"; then
    say "already set in $ENV_FILE — rewriting to be sure"
    sed -i "s#^NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=.*#NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=$CDI_SPEC#" "$ENV_FILE"
  else
    cp -n "$ENV_FILE" "$ENV_FILE.vms-orig" 2>/dev/null || true
    printf '\n%s\n%s\n' "$MARKER" "NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=$CDI_SPEC" >> "$ENV_FILE"
    say "set NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=$CDI_SPEC (backup: $ENV_FILE.vms-orig)"
  fi

  install -d -m 0755 "$CDI_DIR"
  # Generate it now so the fix takes effect without waiting for a reboot.
  if nvidia-ctk cdi generate --output="$CDI_SPEC" >/dev/null 2>&1; then
    say "generated $CDI_SPEC ($(wc -c < "$CDI_SPEC") bytes)"
  else
    say "WARNING nvidia-ctk cdi generate failed — check 'nvidia-ctk cdi generate'"
    return 1
  fi
  # Prove dockerd can resolve it.
  if nvidia-ctk cdi list 2>/dev/null | grep -q 'nvidia.com/gpu=all'; then
    say "verified nvidia.com/gpu=all resolves"
  fi
  say "dockerd picks up /etc/cdi at daemon start; no restart needed for new containers"
}

# ── part 2: boot unit ───────────────────────────────────────────────────────
install_unit() {
  head_ "2. Boot unit"
  [ -f "$UNIT_SRC" ] || { echo "missing template: $UNIT_SRC" >&2; return 1; }
  sed "s#@VMS_DIR@#$VMS_DIR#g" "$UNIT_SRC" > "$UNIT_DST"
  chmod 0644 "$UNIT_DST"
  say "wrote $UNIT_DST (WorkingDirectory=$VMS_DIR)"
  systemctl daemon-reload
  systemctl enable vms.service >/dev/null 2>&1
  say "enabled vms.service — runs '$VMS_DIR/vms up -d' after docker + CDI refresh"
  say "NOT started now: the stack is already up and starting it would be a no-op"
}

do_uninstall() {
  head_ "Uninstall"
  if [ -f "$ENV_FILE" ]; then
    sed -i "\#^$MARKER\$#d; \#^NVIDIA_CTK_CDI_OUTPUT_FILE_PATH=$CDI_SPEC\$#d" "$ENV_FILE"
    say "reverted $ENV_FILE (spec returns to /var/run/cdi on next refresh)"
  fi
  say "left $CDI_SPEC in place — harmless, and removing it re-opens the race"
  if [ -f "$UNIT_DST" ]; then
    systemctl disable --now vms.service >/dev/null 2>&1 || true
    rm -f "$UNIT_DST"
    systemctl daemon-reload
    say "removed and disabled vms.service"
  fi
}

case "$MODE" in
  --check)     do_check ;;
  --cdi-only)  need_root; install_cdi; do_check ;;
  --unit-only) need_root; install_unit; do_check ;;
  --all)       need_root; install_cdi; install_unit; do_check ;;
  --uninstall) need_root; do_uninstall ;;
  *) echo "usage: $0 [--all|--cdi-only|--unit-only|--check|--uninstall]" >&2; exit 1 ;;
esac
